import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Manrope } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import Providers from "@/redux/providers/providers";
import Navbar from "@/components/navbar/navbar";
import LayoutWrapper from "@/components/layoutWrapper/layoutWrapper";
import ThemeLoader from "@/components/themeLoader/themeloader";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "MediCare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={inter.variable} 
      >
        <ThemeLoader/>

        
        <Providers>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
          

        </Providers>
        
      </body>
    </html>
  );
}
